version: '3'
services:
    artifact-draft:
        build: .
        image: artifact-draft
        command: artifact-draft
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - artifact-draft
